apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bwrck-brk-gen.fullname" . }}
  labels:
    {{- include "bwrck-brk-gen.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bwrck-brk-gen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bwrck-brk-gen.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bwrck-brk-gen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: openwire
              containerPort: 1031
              protocol: TCP
            - name: mqtt
              containerPort: 1701
              protocol: TCP
            - name: ws
              containerPort: 1864
              protocol: TCP
            - name: stomp
              containerPort: 2000
              protocol: TCP
            - name: openwire-ssl
              containerPort: 11031
              protocol: TCP
            - name: mqtt-ssl
              containerPort: 11701
              protocol: TCP
            - name: ws-ssl
              containerPort: 11864
              protocol: TCP
            - name: stomp-ssl
              containerPort: 12000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GEN
              value: "false"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
